.TH GRICLI 1 "July 1, 2011" "Gricli user manual"
.SH NAME
.PP
gricli - grid commandline interface
.SH SYNOPSIS
.PP
gricli [\f[I]options\f[]]
.SH DESCRIPTION
.PP
Gricli is a shell that allows commandline interaction with the
grid.
You can use it to submit, control and monitor jobs.
It also supports easy access to grid-filesystems and resource
information.
.PP
Gricli is based on the \f[I]Grisu\f[] framework and can connect to
different \f[I]Grisu backends\f[] by selecting the appropriate one
as a commandline parameter, e.
g.:
.PP
\f[CR]
      gricli\ -b\ BeSTGRID
\f[]
.PP
or
.PP
\f[CR]
      gricli\ -b\ Local
\f[]
.PP
The above first would connect to the default \f[I]BeSTGRID\f[]
backend that publishes the \f[I]Grisu\f[] API via SOAP.
The latter would connect to a local \f[I]Grisu\f[] backend which
sits on the same computer as \f[I]gricli\f[], as long as the local
backend jar
(http://code.ceres.auckland.ac.nz/downloads/local-backend.jar) is
in the classpath (either in the same folder as gricli or in
%$HOME/.grisu.beta/lib/).
.SH OPTIONS
.PP
-b \f[I]BACKEND\f[] or --backend=\f[I]BACKEND\f[]
.PP
The Grisu backend to connect to.
The default is \f[I]BeSTGRID\f[] and other possible backends are
\f[I]BeSTGRID-TEST\f[],\f[I]BeSTGRID-DEV\f[] and \f[I]Local\f[].
.PP
Examples:
.PP
\f[CR]
      gricli\ -b\ BeSTGRID
      gricli\ --backend=BeSTGRID
\f[]
.PP
-f \f[I]SCRIPT\f[] or --file=\f[I]SCRIPT\f[]
.PP
Executes a gricli script.
.PP
Examples:
.PP
\f[CR]
      gricli\ -f\ myexp.gs
      gricli\ --file=myexp.gs
\f[]
.PP
-n or --nologin
.PP
Disables login at gricli startup.
.PP
Example:
.PP
\f[CR]
      gricli\ -n
\f[]
.SH GLOBALS
.SS List of globals:
.SS mai
.SS *
.SH COMMANDS
.SS mai
.SS comma
.SS *
.PP
The Gricli source code and all documentation may be downloaded from
<http://github.com/grisu/gricli>.
.SH AUTHORS
Yuriy Halytskyy, Markus Binsteiner.

