#!/bin/bash

unset DISPLAY
export JAVA_OPTS="-Djava.awt.headless=true -Xms128m -Xmx128m"
export X509_USER_PROXY=~/.grisu/grisu.proxy
java ${JAVA_OPTS} -cp /usr/local/lib/grisu/gricli-binary.jar grisu.gricli.Gricli $@

