#!/bin/sh
# postinst script for gricli
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    	
    	if [ -f /usr/share/keyrings/nesi-repo.key ]; then
			rm /usr/share/keyrings/nesi-repo.key.dpkg-new2
		else
    		echo "Adding nesi debian repo key..."
    		mv /usr/share/keyrings/nesi-repo.key.dpkg-new2 /usr/share/keyrings/nesi-repo.key
			/usr/bin/apt-key add /usr/share/keyrings/nesi-repo.key
		fi
		
		if [ -f /etc/apt/sources.list.d/nesi-repo.list ]; then
			rm /etc/apt/sources.list.d/nesi-repo.list.dpkg-new2
		else
    		mv /etc/apt/sources.list.d/nesi-repo.list.dpkg-new2 /etc/apt/sources.list.d/nesi-repo.list
		fi
    
		;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
		
esac




